// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewwWjxPk0OldkMsCMb3PuS2mVKlIGY58',
    appId: '1:765503043527:web:c2d1583125abcd0049cbe2',
    messagingSenderId: '765503043527',
    projectId: 'recipe-catalog-1d26b',
    authDomain: 'recipe-catalog-1d26b.firebaseapp.com',
    storageBucket: 'recipe-catalog-1d26b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9FtTjeN1raxPJkUGrY3jrqtU2dhikhPw',
    appId: '1:765503043527:android:5bd75e39febfd9f249cbe2',
    messagingSenderId: '765503043527',
    projectId: 'recipe-catalog-1d26b',
    storageBucket: 'recipe-catalog-1d26b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTydYfjLTEAJ6JLVH-FRfHadHC8BqB7k',
    appId: '1:765503043527:ios:592406fd1c6d736649cbe2',
    messagingSenderId: '765503043527',
    projectId: 'recipe-catalog-1d26b',
    storageBucket: 'recipe-catalog-1d26b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTydYfjLTEAJ6JLVH-FRfHadHC8BqB7k',
    appId: '1:765503043527:ios:592406fd1c6d736649cbe2',
    messagingSenderId: '765503043527',
    projectId: 'recipe-catalog-1d26b',
    storageBucket: 'recipe-catalog-1d26b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDewwWjxPk0OldkMsCMb3PuS2mVKlIGY58',
    appId: '1:765503043527:web:65280423b1aa65bf49cbe2',
    messagingSenderId: '765503043527',
    projectId: 'recipe-catalog-1d26b',
    authDomain: 'recipe-catalog-1d26b.firebaseapp.com',
    storageBucket: 'recipe-catalog-1d26b.firebasestorage.app',
  );
}
