// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_final_project/data/models/favorite_model.dart';
import 'package:flutter_final_project/data/models/recipe_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteModelAdapter());
    registerAdapter(RecipeModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteModelAdapter());
    registerAdapter(RecipeModelAdapter());
  }
}
